Models/Client.cs
using System.Collections.Generic;

namespace ECSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Description { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace ECSalon.Models
{
  public class ECSalonContextFactory : IDesignTimeDbContextFactory<ECSalonContext>
  {

    ECSalonContext IDesignTimeDbContextFactory<ECSalonContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<ECSalonContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new ECSalonContext(builder.Options);
    }
  }
}

Models/ECSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace ECSalon.Models
{
  public class ECSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public ECSalonContext(DbContextOptions options) : base(options) { }
  }
}

Models/ECSalonDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace ECSalon.Models
{
  public class ECSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public ECSalonContext(DbContextOptions options) : base(options) { }
  }
}

Models/Stylist.cs
using System.Collections.Generic;

namespace ECSalon.Models
{
  public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<Client>();
        }

        public int StylistId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}

Models/StylistClients.cs
namespace ECSalon.Models
{
  public class StylistClients
    {
        public int StylistClientsId { get; set; }
        public int StylistId { get; set; }
        public int ClientId { get; set; }
        public virtual Stylist Stylist { get; set; }
        public virtual Client Client { get; set; }
    }
}

Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using ECSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly ECSalonContext _db;

    public ClientsController(ECSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECSalon.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    } 
  }
}

Controllers/StylistController.cs
using Microsoft.AspNetCore.Mvc;
using ECSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ECSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly ECSalonContext _db;

    public StylistsController(ECSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Client

<h4>Add a new task</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Add new Client" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Clients", "Index")</p>

Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Client

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>

Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Client

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using ECSalon.Models;
@model List<ECSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No Clients have been added yet!</h3>
}

@foreach (Client client in Model)
{
  <li>@Html.ActionLink($"{client.Description}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
}

<p>@Html.ActionLink("Add new client", "Create")</p>

\

Views/Home/Index.cshtml
@{
Layout = "_Layout";
}

<h1>Welcome to the Eau Clair's Salon!</h1>
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>
<p>@Html.ActionLink("See all clients", "Index", "Clients")</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Eau Clair's Salon</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    @RenderBody()
  </body>
</html>

Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Stylist

<h4>Add a new category</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add new stylist" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Stylist

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to stylists", "Index")

Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using ECSalon.Models;
@model ECSalon.Models.Stylist;

<h2>Stylist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<ul>
@if (@Model.Clients.Count == 0)
{
  <p>no clients found</p>
}

@foreach (Client client in @Model.Clients)
{
  <li>Description: @client.Description</li>
}
</ul>

<p>@Html.ActionLink("Back to stylists", "Index")</p>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>

Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ECSalon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this Stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StylistId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to stylists", "Index")</p>

Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using ECSalon.Models;
@model List<ECSalon.Models.Stylist>;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
}

@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
}

<p>@Html.ActionLink("Add new stylist", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>